export const cards = [
    {
      id: 1,
      title: "T57 ",
      desc: "PCT/TR2010/000255",
      img: "./product/T57.jpg",
    },
    {
      id: 2,
      title: "T58",
      desc: "PCT/TR2010/000255 ",
      img: "./product/T58.jpg",
    },
    {
      id: 3,
      title: "T83",
      desc: "PCT/TR2016/050076 ",
      img: "./product/T83.jpg",
    },
    {
      id: 4,
      title: "T86",
      desc: "PCT/TR2017/050238 ",
      img: "./product/T86.jpg",
    },
    {
      id: 5,
      title: "T86",
      desc: "2017/05930 ",
      img: "./product/T86_2.jpg",
    },
    {
      id: 6,
      title: "T79",
      desc: "2017/06268 ",
      img: "./product/T79.jpg",
    },
    {
      id: 7,
      title: "T78",
      desc: "2017/06268",
      img: "./product/T78.jpg",
    },
    // {
    //   id: 8,
    //   title: "Illustration",
    //   desc: "Color you dreams",
    //   img: "https://images.pexels.com/photos/15032623/pexels-photo-15032623.jpeg?auto=compress&cs=tinysrgb&w=1600&lazy=load",
    // },
  ];
  
  export const patents = [

    {
      id: 1,
      basvuruno:"PCT/TR2010/000227",
      referans:"T57",
      img: "./product/T57.jpg",
      pimg: "./product/T57_patent.jpg",
      imgdetay: ["../productdetay/T57_1.jpg","../productdetay/T57_2.jpg","../productdetay/T57_3.jpg"], 
      bastarihi: "08.11.2010",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "QUICK RESPONSE TIME THERMOSTAT ASSEMBLY",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "This invention relates to a thermostat assembly for cooling circulation systems of the internal combustion engines, to stabilise the coolant temperature in the range of engine's design, featured with that a passage surrounds the thermo-actuator for coolant flow via a hole on its valve to generate a coolant flow from engine block to radiator. By this way thermo-actuator keeps always same temperature with actual engine coolant temperature.",
      document:"https://patentscope.wipo.int/search/docs2/pct/WO2012064293/pdf/GfCZgFM7SSrPlDqCaBtQ5ihQ3IlF1bzq5NtnVEMbk7XUN07dei3f0hUAsAYReyHOZlJO6T4Hk2GyqFTb22Ixw-oLvgnMR6WQaBj0Y2ZXStmM4ztw_y989aI1gmF_PjK3?docId=id00000017396694",
    },

    {
      id: 2,
      basvuruno:"PCT/TR2010/000255",
      referans:"T58",
      img: "./product/T58.jpg",
      pimg: "./product/T58_patent.jpg",
      imgdetay: ["../productdetay/T58_1.jpg","../productdetay/T58_2.jpg","../productdetay/T58_2.jpg"], 
      bastarihi: " 23.12.2010",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "A THERMOSTAT ASSEMBLY FOR INTERNAL COMBUSTION ENGINES",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "This invention relates to a thermostat assembly for cooling circulation systems of the internal combustion engines, to stabilise the coolant temperature in the range of engine's design. The thermostatic valve assembly comprises a thermo-actuator fitted inside the valve; a seal placed on the groove on valve, which obstructs the coolant flow from engine block to radiator at the closed position of the valve and frame placed on the cover and spring, which forces valve for closing when the coolant temperature drops down.",
      document:"https://patentscope.wipo.int/search/docs2/pct/WO2012087252/pdf/WwWI-ofgBRyz7TYrVCC3eSpWid1Qmoi7EvM0ExwPkSfivr4l-dy4lgzYeaugQndgeZV1n3gcHCDsAi2_VsKK_05TLiXwQGgov9I2U5eg0w4DAJB1aUlu5XFaHz5dV35W?docId=id00000017853030",
    },

    {
      id: 3,
      basvuruno:"PCT/TR2016/050076",
      referans:"T83",
      img: "./product/T83.jpg",
      pimg: "./product/T83_patent.jpg",
      imgdetay: ["../productdetay/T83_1.jpg","../productdetay/T83_2.jpg","../productdetay/T83_3.jpg"], 
      bastarihi: "24.03.2016",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "UNENGAGED LOCK SYSTEM",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "This invention relates to an unengaged lock system which is used to assembly the thermostat body parts used in the coolant circulation unit of the internal combustion engines comprises a locked element (3) which has a side surface (31) and teethes (32) and a locking element (2) which has a primary housing (21), secondary housing (22), extension (23) and pawl (24) and which provides a locking by surrounding the locked element (3).",
      document:"https://patentscope.wipo.int/search/docs2/pct/WO2017164826/pdf/CNnY8BNfE3ypALMQUNzBpqGDAHqAO68GruVy6ih2_jeU1kkzaG8VLZcScAlv_7D7vZ1wxUV70FiaT6Ao5TnXAqENgL533mplx1Sou9nkGOkLpi9kgtkwMTip3DLYcjRR?docId=id00000039430495",
     
    },
    
    {
      id: 4,
      basvuruno:"PCT/TR2017/050238 (TR 2016/12859)",
      referans:"T86",
      img: "./product/T86.jpg",
      pimg: "./product/T86_patent.jpg",
      imgdetay: ["../productdetay/T86_1.jpg","../productdetay/T86_2.jpg","../productdetay/T86_3.jpg"], 
      bastarihi: "02.06.2017",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "A THERMO-ACTUATOR AND SEALING ELEMENT ASSEMBLY METHOD - BİR TERMO AKTÜATÖR VE SIZDIRMAZLIK ELEMANI MONTAJ YÖNTEM",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "İçten yanmalı motorların soğutma sirkulasyon devrelerinde kullanılmak üzere, silindirik formda yapılandırılmış bir gövde (11) bahsedilen gövdenin (11) devamında çıkıntı formunda yapılandırılmış bir kademeli çap (12); bahsedilen kademeli çapın (12) civarında konumlanarak sızdırmazlığı sağlayan halka formunda bir conta (20) içeren bir termo-aktüatör (10) olup özelliği; bahsedilen contanın (20); kademeli çapın (12) bir alt yüzeyine (122) yaslanan bir alt dudak (23); kademeli çapın (12) bir yan yüzeyine (121) doğru uzanan bir üst dudak (21); alt dudak (23) ile üst dudak (21) arasında uzanan bir temas boğumu (22) içermesi ve contayı (20) bahsedilen kademeli çap (12) ile aralarında ezerek sıkıştıracak şekilde gövde (11) üzerine sıkı geçme takılan ve gövdeyi (11) uzunluğu doğrultusunda saracak şekilde uzanan bir tutucu kısma (31) sahip bir klepe (30) içermesidir.",
      document:"https://patentscope.wipo.int/search/docs2/pct/WO2018048370/pdf/M4v6DsAo9NiRbeRiJaIupBm6ESqEcpAnh7qiEkpRBz4p1Ov9kOObMAj7mSp62WtIBOycELz4wZf7bXcCzvUZej64GjUhE8JSp4_DvpsLG7Sxe30_zX7-6vhuwD6VDTiU?docId=id00000041646093",
    },

    {
      id: 5,
      basvuruno:"TR 2017/05930 ",
      referans:"T86_2",
      img: "./product/T86_2.jpg",
      pimg: "./product/T86_2_patent.jpg",
      imgdetay: ["../productdetay/T86_2_1.jpg","../productdetay/T86_2_2.jpg","../productdetay/T86_2_3"], 
      bastarihi: "21.04.2017",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "PLASTİK PARÇALARIN DEFORMASYONSUZ BİRLEŞTİRİLMESİ YÖNTEMİ VE BUNUNLA ELDE EDİLEN BİR TERMOSTAT",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş bir plastik parçanın bir noktaya, bölgeye veya başka bir parçaya yerleştirilmesi, iç içe geçme, kenetlenme gibi montaj tekniklerinde ilk montaj esnasında en az bir plastik parçanın tamamının veya bir kısmının esnemesinin gerektiği durumlarda ilgili plastik parçanın bu esnemede deformasyona uğramadan yerleşmesine imkan tanıyan bir plastik parça montaj veya birleştirme yöntemidir. Buluş konusu yöntemde parçanın formunda herhangi bir değişikliğe neden olmadan her bir parçanın kırılma öncesi uzama (EBF) parametresine göre parça sıcaklığı artırılarak kırılganlığını azaltmak veya kırılma öncesi uzama değerini artırmak üzere parçaların boyutlarına uygun teşkil edilerek onların yerleşebileceği biçimde yuvalar ihtiva eden magazinler vasıtasıyla parçaların EBF değerlerinin %5-6 seviyelerine çıkmalarını sağlamak için 80-110 oC ısıtılmalarıyla karakterize edilmesidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/05930&documentsTpye=all",
    },
    {
      id: 6,
      basvuruno:"TR 2016/12859",
      referans:"E04",
      img: "./product/avatar.jpg",
      imgdetay: ["../productdetay/E06_4.jpg","../productdetay/E06_5.jpg","../productdetay/E06_6.jpg"], 
      pimg: "./product/E04_patent.jpg",
      bastarihi: "08.9.2016",
      tesciltarihi:"21.05.2020",
      korumatipi:"Patent",
      title: "BİR TERMO AKTÜATÖR VE SIZDIRMAZLIK ELEMANI MONTAJ YÖNTEMİ",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "İçten yanmalı motorların soğutma sirkulasyon devrelerinde kullanılmak üzere, silindirik formda yapılandırılmış bir gövde (11) bahsedilen gövdenin (11) devamında çıkıntı formunda yapılandırılmış bir kademeli çap (12); bahsedilen kademeli çapın (12) civarında konumlanarak sızdırmazlığı sağlayan halka formunda bir conta (20) içeren bir termo-aktüatör (10) olup özelliği; bahsedilen contanın (20); kademeli çapın (12) bir alt yüzeyine (122) yaslanan bir alt dudak (23); kademeli çapın (12) bir yan yüzeyine (121) doğru uzanan bir üst dudak (21); alt dudak (23) ile üst dudak (21) arasında uzanan bir temas boğumu (22) içermesi ve contayı (20) bahsedilen kademeli çap (12) ile aralarında ezerek sıkıştıracak şekilde gövde (11) üzerine sıkı geçme takılan ve gövdeyi (11) uzunluğu doğrultusunda saracak şekilde uzanan bir tutucu kısma (31) sahip bir klepe (30) içermesidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2016/12859&documentsTpye=all",
    },
    {
      id: 7,
      basvuruno:"TR 2016/15622",
      referans:"E06",
      img: "./product/avatar.jpg",
      imgdetay: ["../productdetay/E06_1.jpg","../productdetay/E06_2.jpg","../productdetay/E06_3.jpg"],     
      pimg: "./product/E06_patent.jpg",
      bastarihi: " 02.11.2016",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "HIZLI REAKSİYON SÜRESİNE SAHİP WAX-BAZLI AKTÜATÖR",
      patentdurumu:"Geçersiz",
      descriptiontitle:"Buluş Özeti",
      description: "İçten yanmalı motorların soğutma sirkülasyonunda kullanılan ve bir piston (2), bahsedilen pistonu (2) en azından kısmen kapatan bir kapak (3), bahsedilen kapağın (3) üzerinde konumlandığı içi boş silindirik bir biçimde yapılandırılan bir hazne (7), haznenin (7) iç tarafına yerleştirilen bir wax bileşikli pelet (5) ve bir ucundan kapağa (3) uzanan ve diğer ucundan wax bileşikli pelete (5) uzanan bir diyafram (4) içeren bir wax-bazlı aktüatör (1) olup özelliği, wax-bazlı aktüatörün (1) reaksiyon süresini azaltmak üzere hazne (7) ile kendi arasına wax bileşikli peletin (5) konumlanması sağlanacak şekilde yerleştirilen silindirik bir çekirdek doldurucu (6) içermesiyle karakterize edilmesidir. Şekil 1",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2016/15622&documentsTpye=all",
    },

    {
      id: 8,
      basvuruno:"TR 2016/16787",
      referans:"E07",
      img: "./product/avatar.jpg",
      pimg: "./product/E07_patent.jpg",
      imgdetay: ["../productdetay/E07_1.jpg","../productdetay/E07_2.jpg","../productdetay/E07_3.jpg"], 
      bastarihi: " 18.11.2016",
      tesciltarihi:"21.01.2020",
      korumatipi:"Patent",
      title: "KENDİNDEN HAVA TAHLİYE VALFLİ TERMOSTAT MEKANİZMASI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Bu buluş, içten yanmalı motorların soğutma sirkülasyon devrelerinden kullanılan bilyalı (B) hava tahliye valfleri için hava deşarjı sağlamak üzere kendinden kafes mekanizması sağlayan kendinden hava tahliye valfli termostat mekanizması (1) ile ilgilidir. Kendinden hava tahliye mekanizması, alt gövde (2) ve üst gövdeden (3) yaratılan oyuklarla ekstra kafes yapısına ihtiyaç olmaksızın sağlanır ve kafes yapısı alt gövde (2) ve üst gövdenin (3) birbirine montajlanması veya kaynaklanması ile oluşturulur.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2016/16787&documentsTpye=all",
    },

    {
      id: 9,
      basvuruno:"TR 2016/16963",
      referans:"E08",
      img: "./product/avatar.jpg",
      pimg: "./product/E08_patent.jpg",
      imgdetay: ["../productdetay/E08_1.jpg","../productdetay/E08_2.jpg","../productdetay/E08_3.jpg"], 
      bastarihi: " 22.11.2016",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "TANDEM TERMAL AKTÜATÖRE SAHİP TERMOSTAT TERTİBATI",
      patentdurumu:"Geçersiz",
      descriptiontitle:"Buluş Özeti",
      description: "İçten yanmalı motorların soğutma devrelerinde kullanım için geliştirilmiş ve bir kap içerisine hapsedilen termal olarak duyarlı bir bileşeni içeren en az bir termal elemana (22), bahsedilen kap üzerinde konumlanan bir kapağa (23), bahsedilen kapağın (23) iç kısmından dışarı doğru hareket edebilir şekilde sağlanan bir pistona (24) sahip bir termal aktüatörü (2) içeren bir termal tertibat (1) olup özelliği, içerisinde karşıt yönlerde arka arkaya konumlanmış en az iki termal elemanın (22) bulunduğu ve termal elemanları (22) en azından kısmen çevreleyen bir burç kapsülü (21) içermesidir. Şekil 1",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2016/16963&documentsTpye=all",
    },
       
    {
      id: 10,
      basvuruno:"TR 2017/05591",
      referans:"E09",
      img: "./product/avatar.jpg",
      pimg: "./product/E09_patent.jpg",
      imgdetay: ["../productdetay/E09_1.jpg","../productdetay/E09_2.jpg","../productdetay/E09_3.jpg"], 
      bastarihi: " 14.4.2017",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "ÇİFT AKIŞ SAĞLANAN BASINÇ DENGELİ BORU TİP KLAPELİ TERMOSTAT MEKANİZMASI",
      patentdurumu:"Geçersiz",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, yüksek debilerde düşük basınç düşümü sağlamak amacuyla eş zamanlı olarak çift port açışına izin veren klepe yatağı (3) ve çift akışlı boru tipi klepe (2) içeren, içten yanmalı motorların soğutma sirkülasyon devreleri için bir çift akış sağlanan basınç dengeli boru tipi klepeli termostat mekanizması ile ilgilidir. Klepe mekanizması; sızdırmazlık elemanları sayesinde (214,32) sızdırmaz yapıda olan ve kolayca uygulanabilen boru tipi klepe (2) ve eşeksenli klepe yatağının (3) bir montajıdır.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/05591&documentsTpye=all",
    },

    {
      id: 11,
      basvuruno:"TR 2017/06080",
      referans:"E10",
      img: "./product/avatar.jpg",
      pimg: "./product/E10_patent.jpg",
      imgdetay: ["../productdetay/E10_1.jpg","../productdetay/E10_2.jpg","../productdetay/E10_3.jpg"], 
      bastarihi: " 25.4.2017",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "ETKİN BİR ISI AKTARIM ÇÖZÜMÜNE SAHİP İLÂVE BİR ELEKTRİKLİ ISITICININ KULLANILMASIYLA MOTOR SOĞUTKANININ HIZLI ISITILMASI",
      patentdurumu:"Geçersiz",
      descriptiontitle:"Buluş Özeti",
      description: "Motorun ilk çalışmasında soğuk çalışmasını önlemek üzere geliştirilmiş içten yanmalı motorların soğutma devresinde kullanılan ve bir gövde (20); bahsedilen gövde (20) üzerinde yapılandırılmış bir hazne (21); gövde (20) üzerinde konumlanan bir kapak (50); kapak (50) üzerinde yapılandırılan en az bir kapak ısıtıcı yuvasından (51) geçerek hazne (21) içerisinden geçen sıvıyı ısıtan bir ısıtıcı (30) içeren hızlı ısıtma cihazı (10) olup özelliği, söz konusu hazne (21) içerisine yerleşen ve en az bir ısıtıcı (30) ile temas eden ve daha geniş temas yüzeyi sağlayarak sıvının ısınma süresini kısaltan ve aşırı ısınmadan kaynaklanan kaynama risklerini elimine eden en az bir serpantin (40) içermesidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/06080&documentsTpye=all",
    },

    {
      id: 12,
      basvuruno:"TR 2017/06268",
      referans:"E12",
      img: "./product/avatar.jpg",
      pimg: "./product/E12_patent.jpg",
      imgdetay: ["../productdetay/E12_1.jpg","../productdetay/E12_2.jpg","../productdetay/E12_3.jpg"], 
      bastarihi: " 27.4.2017",
      tesciltarihi:"23.03.2020",
      korumatipi:"Patent",
      title: "DÜŞÜK SICAKLIKLI ORTAMDA YÜKSEK SICAKLIKLI BAŞKA BİR ORTAMI REGÜLE EDEN TERMOSTAT MEKANİZMASI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, düşük sıcaklıklı ortamda yüksek sıcaklıklı başka bir ortamı regüle eden termostat mekanizması ile ilgili olup, termo-aktüatöre (1) sadece sıcaklığı ölçülmek istenen sıvı girişine müsaade ederek bir nevi izolasyon elemanı olarak çalışan, içerisindeki sıvının termo-aktüatörün (1) cidarlarına temasını sağlayarak sıcaklık algılama kalitesini arttıran bir klepe (3), hammaddesi nedeniyle soğutucu sıvının sızmasını engelleyen bir sızdırmazlık elemanı (2), klepe (3) içerisindeki sıvının termo-aktüatör (1) ile temasının sağlandıktan sonra yerine yeni sıvının gelebilmesi için klepeden (3) uzaklaştıran bir delik (9) içerir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/06268&documentsTpye=all",
    },
    
    {
      id: 13,
      basvuruno:"TR 2020/06982",
      referans:"E13",
      img: "./product/avatar.jpg",
      pimg: "./product/E13_patent.jpg",
      imgdetay: ["../productdetay/E13_1.jpg","../productdetay/E13_2.jpg","../productdetay/E13_3.jpg"], 
      bastarihi: " 5.5.2020",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "TERMO-ELEMANIN TERMOSTAT ÇIKIŞ SICAKLIĞINI ALGILAMASINI SAĞLAYAN BİR VALF YAPISI VE BUNA İLİŞKİN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş, bypass giriş (11) ve radyatör girişten (12) gelen soğutucuların termo-aktüatöre (20) ulaşana kadar karıştırılmasını sağlayarak termostat çıkış (13) sıcaklığına göre valf kontrolü sergileyen, motor tertibatlarında soğutucuların sıcaklığını düzenlemek üzere düzenlenmiş bir termostat tertibatı (1) ve bu tertibata haiz soğutma düzeneği ile ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2020/06982&documentsTpye=all",
    },
    {
      id: 14,
      basvuruno:"TR 2017/05930",
      referans:"B01",
      img: "./product/avatar.jpg",
      pimg: "./product/B01_patent.jpg",
      imgdetay: ["../productdetay/B01_1.jpg","../productdetay/B01_2.jpg","../productdetay/B01_3.jpg"], 
      bastarihi: " 21.4.2017",
      tesciltarihi:"21.09.2020",
      korumatipi:"Patent",
      title: "PLASTİK PARÇALARIN DEFORMASYONSUZ BİRLEŞTİRİLMESİ YÖNTEMİ VE BUNUNLA ELDE EDİLEN BİR TERMOSTAT",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş bir plastik parçanın bir noktaya, bölgeye veya başka bir parçaya yerleştirilmesi, iç içe geçme, kenetlenme gibi montaj tekniklerinde ilk montaj esnasında en az bir plastik parçanın tamamının veya bir kısmının esnemesinin gerektiği durumlarda ilgili plastik parçanın bu esnemede deformasyona uğramadan yerleşmesine imkan tanıyan bir plastik parça montaj veya birleştirme yöntemidir. Buluş konusu yöntemde parçanın formunda herhangi bir değişikliğe neden olmadan her bir parçanın kırılma öncesi uzama (EBF) parametresine göre parça sıcaklığı artırılarak kırılganlığını azaltmak veya kırılma öncesi uzama değerini artırmak üzere parçaların boyutlarına uygun teşkil edilerek onların yerleşebileceği biçimde yuvalar ihtiva eden magazinler vasıtasıyla parçaların EBF değerlerinin %5-6 seviyelerine çıkmalarını sağlamak için 80 ? 110 oC ısıtılmalarıyla karakterize edilmesidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/05930&documentsTpye=all",
    },

    {
      id: 15,
      basvuruno:"TR 2017/07791",
      referans:"B02",
      img: "./product/avatar.jpg",
      pimg: "./product/B02_patent.jpg",
      imgdetay: ["../productdetay/B02_1.jpg","../productdetay/B02_2.jpg","../productdetay/B02_3.jpg"], 
      bastarihi: " 29.5.2017",
      tesciltarihi:"21.10.2021",
      korumatipi:"Patent",
      title: "BASINÇ DAYANIMI ARTIRILMIŞ BİR DİYAFRAMA SAHİP AKTÜATÖR",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, bir termostat içindeki ısı değişimini mekanik bir değişime dönüştüren ve ısı geçirgen bir hazne (20), bir piston (40), haznenin (20) üzerine sabitlenen ve pistonu (40) kılavuzlayan bir flanş (60), hazne (20) içinde ısıya duyarlı bir biçimde hacmi artarak bulunduğu haznede (20) basınç artışına yol açan vaks (50) ihtiva eden bir atküatörde (10); vaksın (50) uyguladığı basınçla esneyerek bahsedilen pistonu (50) mekanik olarak hareketlendiren bir diyaframdır (30). Buluş konusu diyaframın (30) hazne (20) ve flanş (60) arasında sıkıştırılarak sızdırmazlığın sağlandığı bölgede basınca dayanımını artırmak üzere bir hazne temas yüzeyi (33) ve diyaframın (30) vaks (50) ile temas halindeki dış yüzeyi arasında bir girinti (31) ve çıkıntı (32) ile teşkil edilen bir dudak yapısı içermektedir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/07791&documentsTpye=all",
    },

    {
      id: 16,
      basvuruno:"TR 2017/14299",
      referans:"B03",
      img: "./product/avatar.jpg",
      pimg: "./product/B03_patent.jpg",
      imgdetay: ["../productdetay/B03_1.jpg","../productdetay/B03_2.jpg","../productdetay/B03_3.jpg"], 
      bastarihi: " 26.9.2017",
      tesciltarihi:"21.07.2020",
      korumatipi:"Patent",
      title: "GELİŞTİRİLMİŞ BYPASS KONTROLÜNE SAHİP TERMOSTAT TERTİBATI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş, tamamen açık termostat pozisyonunda valf (10) üzerine dizayn edilmiş kanallar (14) aracılığıyla bypass girişten (32.1) çıkışa (32.3) doğru sağladığı kılavuz akışla (P) termo-aktüatörün (38) ısı duyarlı wax dolu gövdesi (38.2) etrafında sıcak soğutucu birikimini engelleyen termostat tertibatıyla (32) ilgilidir. Tamamen açık termostat pozisyonunda bahsedilen sıcak soğutucu birikimi, ısı duyarlı wax dolu gövdenin (38.2) ana akış (M) sıcaklığını hissedememesine neden olur. Buluş konusu valf (10) yapısının üzerine dizayn edilmiş kanalların (14) yanı sıra temas alanının (38.3) azaltılmasıyla genişletilen ısı transfer alanıyla (38.4) geliştirilmiş bypass kontrolü amaçlanmıştır.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/14299&documentsTpye=all",
    },

    {
      id: 17,
      basvuruno:"TR 2017/14314",
      referans:"B04",
      img: "./product/avatar.jpg",
      pimg: "./product/B04_patent.jpg",
      imgdetay: ["../productdetay/B04_1.jpg","../productdetay/B04_2.jpg","../productdetay/B04_3.jpg"], 
      bastarihi: " 26.9.2017",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "TAMAMEN KAPALI TERMOSTAT POZİSYONUNDA ISI DUYARLI WAX DOLU GÖVDENİN DOĞRUDAN VE DOLAYLI SOĞUMASININ ENGELLENDİĞİ BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Geçersiz",
      descriptiontitle:"Buluş Özeti",
      description: "Isı duyarlı wax dolu gövde (38.2) üzerine monte edilmiş iletken olmayan bir valf yapısı (10) ve bahsedilen iletken olmayan valf yapısı (10) üzerindeki bir oyuğa (11) yerleştirilmiş bir sızdırmazlık elemanı (20) sayesinde termostatın tamamen kapalı pozisyonunda termostat tertibatı (30) içerisindeki termo-aktüatörün (38) ısı duyarlı wax dolu gövdesinin (38.2) sırasıyla dolaylı ve doğrudan soğumasının engellendiği bir termostat tertibatıyla (30) ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/14314&documentsTpye=all",
    },

    {
      id: 18,
      basvuruno:"TR 2017/18755",
      referans:"B05",
      img: "./product/avatar.jpg",
      pimg: "./product/B05_patent.jpg",
      imgdetay: ["../productdetay/B05_1.jpg","../productdetay/B05_2.jpg","../productdetay/B05_3.jpg"], 
      bastarihi: " 24.11.2017",
      tesciltarihi:"21.06.2022",
      korumatipi:"Patent",
      title: "VAKS BAZLI TERMOSTATIN ÇALIŞMA SICAKLIĞI ARALIĞININ GENİŞLETİLMESİ",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, bir valf (12) yapısı beraber kılavuzlayan bir birinci termo-aktüatör (20) ve bir ikinci termo-aktüatör (30) içeren termostat tertibatıyla (10) ilgilidir. Bahsedilen termo-aktüatörler birbirinden farklı açılmaya başlama ve tamamen açık olma sıcaklıklarına sahiptir. İkinci termo-aktüatörün (30) açılmaya başlama ve birinci termo-aktüatörün (20) tamamen açık olma zaman aralığında bu termo-aktüatörlerden gelen toplam kursa (vuruşa) göre bahsedilen valf (12) yapısı ileri ve geri hareket ettirilir. Her bir termo-aktüatörden gelen çalışma sıcaklığı aralığı onların açılmaya başlama ve tamamen açık olma sıcaklıklarına göre belirlenir. Böylece termostat tertibatı (10), beraber çalışarak geniş çalışma sıcaklık aralığında kontrol kabiliyeti sağlayan farklı sıcaklık-aktivasyonlu termo-aktüatörler sayesinde devridaim eden motor soğutucusunun kontrolünde doğruluk sağlar.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/18755&documentsTpye=all",
    },

   
    {
      id: 19,
      basvuruno:"TR 2017/19196",
      referans:"B06",
      img: "./product/avatar.jpg",
      pimg: "./product/B06_patent.jpg",
      imgdetay: ["../productdetay/B06_1.jpg","../productdetay/B06_2.jpg","../productdetay/B06_3.jpg"], 
      bastarihi: " 30.11.2017",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "BASINÇ DÜŞÜMÜNÜ AZALTAN İYİLEŞTİRİLMİŞ AKIŞ GEOMETRİSİNE SAHİP TERMOSTAT YUVASI ",
      patentdurumu:"Geçersiz",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş, geleneksel yuva içindeki soğutucu kısımları arasındaki basınç farkları yüzünden ölü noktalarda (22) oluşan vorteksleri (23) engelleyen bir termostat yuvasıyla (10) ilgilidir ve böylece soğutucunun yuva boyunca seyri sırasında gerçekleşen basınç düşümünde iyileşme sağlar. Bu iyileşme termostat yuvasının (10) giriş (20) ve dirsek (30) geometrileri değiştirilerek elde edilmiştir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2017/19196&documentsTpye=all",
    },
    {
      id: 20,
      basvuruno:"TR 2018/00656",
      referans:"B07",
      img: "./product/avatar.jpg",
      pimg: "./product/B07_patent.jpg",
      imgdetay: ["../productdetay/B07_1.jpg","../productdetay/B07_2.jpg","../productdetay/B07_3.jpg"], 
      bastarihi: " 17.1.2018",
      tesciltarihi:"21.01.2022",
      korumatipi:"Patent",
      title: "SOĞUTMA SİSTEMİ ÜZERİNDEKİ FARKLI MOTOR ALGILAMA NOKTALARININ SICAKLIK DEĞERLERİNE UYUMLU OLACAK ŞEKİLDE EŞZAMANLI AKTİVE EDİLEN TERMOSTATİK VALF",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, geleneksel üç-yollu vaks-bazlı termostat tertibatlarındaki (10) giriş (11.2), bypass çıkış (11.1) ve radyatör çıkış (11.3) kanallarının yanı sıra bir algılama giriş (11.4) ve bir algılama radyatör çıkış (11.5) kanalı içeren bir vaks-bazlı termostat tertibatıyla (10) ilgilidir. Ayrıca mevcut termostat tertibatı (10), beraber çalışarak bypass çıkış (11.1) ve radyatör çıkış (11.3) açıklıklarını dolayısıyla da bypass çıkış (11.1) ve radyatör çıkış (11.3) arasındaki soğutucu akış oranını belirleyen tandem termo-aktüatörler içermektedir. Her bir aktüatör motor soğutma sistemi üzerindeki farklı bir algılama noktasına göre çalışmaktadır. Birinci termo-aktüatör (20) motor kanallarından mevcut termostat tertibatının (10) girişine (11.2) gelen motor çıkış (Eo) soğutucusunun sıcaklık değerine göre çalışmaktadır. İkinci termo-aktüatör (30) radyatör (R) kanallarından ve/veya mevcut termostat tertibatının (10) bypass çıkışından (11.1) tertibatın algılama girişine (11.4) gelen motor giriş (Ei) soğutucusunun sıcaklık değerine göre çalışır. Böylece her bir aktüatörün kurs değeri, algılama noktaları boyunca akan soğutucunun sıcaklık değerine göre belirlenir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2018/00656&documentsTpye=all",
    },

    {
      id: 21,
      basvuruno:"TR 2018/00657",
      referans:"B08",
      img: "./product/avatar.jpg",
      pimg: "./product/B08_patent.jpg",
      imgdetay: ["../productdetay/B08_1.jpg"], 
      bastarihi: " 17.1.2018",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "TERMAL ELEMANLARIN TEPKİ SÜRESİNDE İYİLEŞME SAĞLAYAN VE İYİLEŞMENİN SÜRDÜRÜLEBİLİRLİĞİNE OLANAK VEREN BİR HİDROLİK SIVI KARIŞIMI",
      patentdurumu:"Başvuru aşamasında - İnceleme raporu bekl.",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş, içerisindeki parafinin ısıl iletkenlik katsayısı yüksek olan grafen ile karışması sonucu artan ısıl iletkenlik katsayısı sayesinde termo-elemanların tepki süresinde kayda değer bir iyileşme sağlayan aynı zamanda içerisindeki borun karışımın grafeni yeterince ıslatmasını sağlayan parafin içerisindeki ıslatma (wetting) etkisi ve grafenin nano ölçeklerdeki yapısı sayesinde homojene yakın bir dağılım gösteren böylece hem ısı transfer yüzeyi boyunca ısı transferinin hızlanmasına hem de içerisinde kullanıldıkları termo-elemanların tepki süresinde sağladıkları iyileşmenin uzun kullanımlar boyunca değişmeden sürdürülebilirliğine olanak veren bir hidrolik sıvı karışımıyla ilgilidir. Termo-elemanların tepki sürelerinde iyileşme sağlamak üzere bilinen teknikte parafin bileşeni içerisine eklenen grafit, expanded grafit ve organic modified expanded grafit malzemelerine kıyasla grafen malzemesi çok daha yüksek ısıl iletkenlik katsayısına sahiptir. Ayrıca bahsedilen grafit, expanded grafit ve organic modified expanded grafit malzemelerinin yapılarının mikro ölçeklerde olması bu malzemelerin parafin bileşeni içerisinde yeterince homojen bir karışım oluşturmalarını engelleyerek bu durum ileriki zamanlarda parafin-eklenen malzeme ayrışmasıyla sonuçlanmakta, bu yüzden bahsedilen malzemelerle oluşturulan hidrolik karışımları ihtiva eden termo-elemanların başlangıçta sağladıkları iyileşme zaman geçtikçe azalmaktadır.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2018/00657&documentsTpye=all",
    },

    {
      id: 22,
      basvuruno:"TR 2018/01512",
      referans:"B09",
      img: "./product/avatar.jpg",
      pimg: "./product/B09_patent.jpg",
      imgdetay: ["../productdetay/B09_1.jpg","../productdetay/B09_2.jpg","../productdetay/B09_3.jpg"], 
      bastarihi: "2.2.2018",
      tesciltarihi:"21.07.2020",
      korumatipi:"Patent",
      title: "HERHANGİ EK BİR OPERASYON VEYA PARÇA GEREKTİRMEKSİZİN TERMO-AKTÜATÖRÜN VALF YAPISI İÇİRİSİNE SIKI GEÇİRİLMESİYLE HAVA TAHLİYE VALFİ OLUŞTURMA YÖNTEMİ VE BUNA İLİŞKİN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş kaynak, herhangi ek yapıştırma operasyonu veya ek parça gerektirmeksizin termoaktüatörün (50) valf yapısı (30) içerisine sıkı geçirilmesiyle valf yapısının (30) yan duvarında oluşturulmuş bir bilya yuva (30.2) deliği içerisine bir bilyanın (31) kilitlenmesine olanak veren bir hava tahliye valfi oluşturma yöntemi ve buna ilişkin bir termostat tertibatıyla (10) ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2018/01512&documentsTpye=all",
    },

    {
      id: 24,
      basvuruno:"TR 2018/06754",
      referans:"B11",
      img: "./product/avatar.jpg",
      pimg: "./product/B11_patent.jpg",
      imgdetay: ["../productdetay/B11_1.jpg","../productdetay/B11_2.jpg","../productdetay/B11_3.jpg"], 
      bastarihi: "14.5.2018",
      tesciltarihi:"21.10.2021",
      korumatipi:"Patent",
      title: "YÜKSEK SIZDIRMAZLIK PERFORMANSI KAZANDIRILMIŞ VALF YAPISI VE BUNA İLİŞKİN TERMOSTAT TERTİBATI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, termo-aktüatörün (30) tamamen açık pozisyonunda ve termo-aktüatörün (30) tamamen kapalı pozisyonunda sırasıyla bypass çıkış geçidi penceresine (12.1) ve radyatör çıkış geçidi penceresine (13.1) doğru yay özellik sergileyen o-conta (26) gömülü kısımları sayesinde valf yapısının (20) dış yüzeyi ile gövdenin (10) iç yüzeyi arasındaki açıklığı (50) lokasyonel olarak telafi ederek bypass çıkış geçidi penceresinde (12.1) ve radyatör çıkış geçidi penceresinde (13.1) sızdırmazlık sağlayan bir valf yapısı (20) içeren termostat tertibatıyla (1) ilgilidir. Mevcut valf yapısı (20) giriş (11) ile bypass çıkış (12)/radyatör çıkış (13) arasında sırasıyla valf yapısının (20) tamamen açık/tamamen kapalı pozisyonlarında yüksek sızdırmazlık performansı sergilemektedir. Böylece, valf yapısı (20) ve gövde (10) arasındaki (termostat iç boşluğundaki valf hareketi için gerekli olan) açıklığa (50) rağmen bahsedilen o-conta (26) gömülü kısımlar motor soğutma sistemlerinin hassas sıcaklık kontrolü için gerekli olan sızdırmazlığı sağlamayı mümkün hale getirmektedir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2018/06754&documentsTpye=all",
    },

    {
      id: 25,
      basvuruno:"TR 2019/05307",
      referans:"B16",
      img: "./product/avatar.jpg",
      pimg: "./product/B16_patent.jpg",
      imgdetay: ["../productdetay/B16_1.jpg","../productdetay/B16_2.jpg","../productdetay/B16_3.jpg"], 
      bastarihi: "9.4.2019",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "VALF HAREKETİNİN DENGESİNİ SAĞLAYARAK VALF VE GÖVDE ARASINDAKİ SÜRTÜNMEYİ MİNİMİZE EDEN TERMOSTAT TERTİBATI",
      patentdurumu:"Başvuru aşamasında - İnceleme raporu bekl.",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş, valf hareketinde denge sağlayarak valf yapısının (20) dış yüzeyi ile termostat gövdesinin (10) iç yüzeyi arasındaki sürtünmeyi minimize eden, basınç düşümünde ve termostatın tepki süresinde yay (15) elemanın istenmeyen faktör olmasını engelleyen bir vaks-bazlı termostat tertibatına (1) ilişkindir. Burada, valf yapısı (20) ile gövde (10) arasında oluşturulan karşılıklı pozisyonlara iki yay (15) yerleştirilmektedir. Böylece, söz konusu karşılıklı yaylar (15) valf yapısının (20) termostat iç boşluğu (10.1) boyunca dengeli bir şekilde hareket etmesi sağlayarak hareket yüzeyleri boyunca korozyon oluşumunu engellemektedir. Dahası mevcut buluş, yay (15) elemanı soğutucu akış yolunun dışarısında konumlayarak yay (15) elemanın termostat iç boşluğu (10.1) boyunca soğutucu akışın karşısında bir engel teşkil etmesini engellemektedir. Ayrıca, burada, yay (15) eleman ile ısı duyarlı rezervuar (31) arasında doğrudan bir temas söz konusu olmadığından mevcut buluş kısa tepki süresine haizdir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/05307&documentsTpye=all",
    },

    {
      id: 26,
      basvuruno:"TR 2018/13363",
      referans:"B12",
      img: "./product/avatar.jpg",
      pimg: "./product/B12_patent.jpg",
      imgdetay: ["../productdetay/B12_1.jpg","../productdetay/B12_2.jpg","../productdetay/B12_3.jpg"], 
      bastarihi: "18.9.2018",
      tesciltarihi:"21.01.2022",
      korumatipi:"Patent",
      title: "VALF KONTROLÜ İÇİN GEREKEN KUVVETİ MİNİMİZE EDEN BİR VALF YAPISI VE BUNA İLİŞKİN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, valf yapısına (30) üstten ve alttan etki eden soğutucu basınçlarının eşitlenmesine izin vererek valf yapısının (30) kontrolü için gereken kuvvet büyüklüğünü azaltan bir valf yapısı (30) ve ona ilişkin bir termostat tertibatıyla (1) ilgilidir. Termostat iç boşluğu (15) ve basınç denge odası (14) arasındaki basınç tahliyesi, basınç tahliye odası (14) içerisindeki soğutucuyla temas halindeki üst valf elemanı (31) ve termostat iç boşluğu (15) içerisindeki soğutucuyla temas halindeki alt valf elemanı (32) arasında bahsedilen valf yapısı (30) boyunca oluşturulmuş olan bir basınç denge kanalıyla (33) sağlanmaktadır.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2018/13363&documentsTpye=all",
    },

    {
      id: 27,
      basvuruno:"TR 2019/00313",
      referans:"B13",
      img: "./product/avatar.jpg",
      pimg: "./product/B13_patent.jpg",
      imgdetay: ["../productdetay/B13_1.jpg","../productdetay/B13_2.jpg","../productdetay/B13_3.jpg"], 
      bastarihi: "10.1.2019",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "MOTOR SOĞUTMA İÇİN BİR AKILLI TERMAL YÖNETİM MODÜLÜ",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, motor kontrol ünitesinden (ECU) bağımsız bir şekilde, içerisine yerleştirilen bir sıcaklık sensörü (20) tarafından ölçülen sıcaklık değerine göre bypass devresi ve radyatör devresi arasındaki akış oranını otonom bir şekilde kontrol eden bir akıllı termal yönetim modülüne (1) ilişkindir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/00313&documentsTpye=all",
    },

    {
      id: 28,
      basvuruno:"TR 2019/06376",
      referans:"B17",
      img: "./product/avatar.jpg",
      pimg: "./product/B17_patent.jpg",
      imgdetay: ["../productdetay/B17_1.jpg","../productdetay/B17_2.jpg","../productdetay/B17_3.jpg"], 
      bastarihi: "29.4.2019",
      tesciltarihi:"21.01.2022",
      korumatipi:"Patent",
      title: "VALF HİZALAMA YAPISINA HAİZ TERMOSTAT TERTİBATI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, valfin kendi ekseninde herhangi bir yanlış hizalama problemini önleyen valf hizalama yapısını içeren bir termostat tertibatıyla ilgilidir. Spesifik olarak mevcut buluş, piston ucunun piston yuvasından çıkmasına neden olan ekstrem durumlar sırasında valf yapısının merkezlenmesini ve böylece pistonun merkezlenmesini sağlayan ayak yapılarına haiz bir adaptörle ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/06376&documentsTpye=all",
    },

    {
      id: 29,
      basvuruno:"TR 2019/09912",
      referans:"B18",
      img: "./product/avatar.jpg",
      pimg: "./product/B18_patent.jpg",
      imgdetay: ["../productdetay/B18_1.jpg","../productdetay/B18_2.jpg","../productdetay/B18_3.jpg"], 
      bastarihi: "3.7.2019",
      korumatipi:"Patent",
      title: "KONTROLLÜ SOĞUTUCU AKIŞINA İZİN VEREN VALF YAPISI",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, valfin kendi ekseninde herhanBuluş, radyatör penceresinin açılışında kontrollü kademeli artış sağlayan termostat tertibatıyla (10) ilgilidir. Daha spesifik olarak, mevcut buluş radyatör ve termostat iç boşluğu (10.1) arasında kontrollü soğutucu akışına izin veren valf elemanı içeren bir valf yapısıyla (15) ilgilidir.gi bir yanlış hizalama problemini önleyen valf hizalama yapısını içeren bir termostat tertibatıyla ilgilidir. Spesifik olarak mevcut buluş, piston ucunun piston yuvasından çıkmasına neden olan ekstrem durumlar sırasında valf yapısının merkezlenmesini ve böylece pistonun merkezlenmesini sağlayan ayak yapılarına haiz bir adaptörle ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/09912&documentsTpye=all",
    },

    {
      id: 30,
      basvuruno:"TR/2019/14833",
      referans:"B19",
      img: "./product/avatar.jpg",
      pimg: "./product/B19_patent.jpg",
      imgdetay: ["../productdetay/B19_1.jpg","../productdetay/B19_2.jpg","../productdetay/B19_3.jpg"], 
      bastarihi: "30.9.2019",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "KARIŞMA ORANINI OTONOM BİR ŞEKİLDE AYARLAYARAK SABİT ÇIKIŞ SICAKLIĞI SAĞLAYAN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, soğuk ve sıcak soğutucu arasındaki karıştırma oranını otonom bir şekilde ayarlayarak sabit çıkış sıcaklığı sağlayan bir termostat tertibatıyla ilgilidir. Daha spesifik olarak mevcut buluş, belirlenen sabit sıcaklık değerine göre çıkış sıcaklığını düzenleyen bir termostat tertibatıyla ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/14833&documentsTpye=all",
    },

    {
      id: 31,
      basvuruno:"TR 2019/20331",
      referans:"B20",
      img: "./product/avatar.jpg",
      pimg: "./product/B20_patent.jpg",
      imgdetay: ["../productdetay/B20_1.jpg","../productdetay/B20_2.jpg","../productdetay/B20_3.jpg"], 
      bastarihi: "16.12.2019",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "YALNIZCA MOTOR ÇIKIŞINDAN GELEN SOĞUTUCUNUN SICAKLIĞINA GÖRE REAKSİYON VEREN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Mevcut buluş, birden fazla girişe sahip termostat tertibatlarında termostatın yalnızca motor çıkışından gelen soğutucunun sıcaklığına göre reaksiyon vermesini sağlayan bir valf yapısıyla ilgilidir. Daha spesifik olarak mevcut buluş, termo-aktüatörün diğer girişlerden (motor çıkıştan gelen soğutucu hariç) gelen soğutucunun sıcaklığını algılamasını engelleyen bir valf yapısına haiz bir termostat tertibatıyla ilgilidir. Dahası mevcut buluş, soğutma sistemi dışındaki herhangi bir sistem çıkışından gelen her girişin önüne konumlandırılmış en az bir saptırıcı eleman içeren bir valf yapısıyla ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/20331&documentsTpye=all",
    },

    {
      id: 32,
      basvuruno:"TR 2019/19504",
      referans:"B21",
      img: "./product/avatar.jpg",
      pimg: "./product/B21_patent.jpg",
      imgdetay: ["../productdetay/B21_1.jpg","../productdetay/B21_2.jpg","../productdetay/B21_3.jpg"], 
      bastarihi: "7.12.2019",
      tesciltarihi:"21.06.2022",
      korumatipi:"Patent",
      title: "ISITICI PORTUNA DOĞRU OLAN AKIŞ MİKTARINI DÜZENLİ OLARAK AYARLAYAN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Tescilli",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, her motor koşulu için kabin ısıtma sistemine sabit enerji transferi sağlamak üzere ısıtıcı portuna (girişi) doğru olan soğutucu akış miktarını düzenli olarak ayarlayan bir termostat tertibatına ilişkindir. Daha spesifik olarak mevcut buluş, ısıtıcı portu için hem sürekli açık hem de koşullu olarak açık besleme kanalına sahip olan bir termostat tertibatına ilişkindir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2019/19504&documentsTpye=all",
    },

    {
      id: 33,
      basvuruno:"TR 2020/17105",
      referans:"B22",
      img: "./product/avatar.jpg",
      pimg: "./product/B22_patent.jpg",
      imgdetay: ["../productdetay/B22_1.jpg","../productdetay/B22_2.jpg","../productdetay/B21_3.jpg"], 
      bastarihi: "26.10.2020",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "HASSAS SICAKLIK KONTROLÜ SAĞLAYAN HARİTA KONTROLLÜ TERMOSTAT TERTİBATI",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, hassas sıcaklık kontrolü sağlayan bir harita kontrollü termostat tertibatıyla (10) ilgilidir. Daha spesifik olarak mevcut buluş, valf (10) elemanın bir sensör vasıtasıyla ölçülen gerçek açılma değerlerine göre hassas sıcaklık kontrolü sağlayan bir harita kontrollü termostat tertibatı (10) ile ilgilidir. Bu buluş sayesinde ECU?nun, pistona (42) uygulanan elektrik enerjisine karşı gerçekleşen valf (20) açılma miktarının gerçek verilerini analiz etmesi mümkün olmaktadır.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2020/17105&documentsTpye=all",
    },

    {
      id: 34,
      basvuruno:"TR 2020/18670",
      referans:"B24",
      img: "./product/avatar.jpg",
      pimg: "./product/B24_patent.jpg",
      imgdetay: ["../productdetay/B24_1.jpg","../productdetay/B24_2.jpg","../productdetay/B24_3.jpg"], 
      bastarihi: "20.11.2020",
      tesciltarihi:"-",
      korumatipi:"Patent",
      title: "TERMO ELEMAN VE VALF YAPISI ARASINDA MONTAJ KOLAYLIĞI SAĞLAYAN BİR TERMOSTAT TERTİBATI",
      patentdurumu:"Başvuru aşamasında",
      descriptiontitle:"Buluş Özeti",
      description: "Buluş, termo eleman (40) ve valf yapısının birbirine kolay bir şekilde irtibatlandırıldığı bir termostat tertibatıyla (10) ilgilidir. Daha spesifik olarak mevcut buluş, valf yapısı üzerinde içeriye doğru oluşturulmuş tırnak yapılarının (32), termo elemanın (40) hazne (41) kısmının dış yüzeyi etrafında oluşturulan halka şeklinde oluk yapısına (41.1) yerleştiği, böylece termo eleman (40) ile valf yapısı arasındaki montajın kolaylıkla sağlandığı bir termostat tertibatı (10) ile ilgilidir.",
      document:"https://portal.turkpatent.gov.tr/anonim/arastirma/patent/sonuc/dosya?patentAppNo=2020/18670&documentsTpye=all",
    },

    

  ];
  
  export const gigs = [
    {
      id: 1,
      img: "https://images.pexels.com/photos/580151/pexels-photo-580151.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720598/pexels-photo-720598.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai art character from your images and prompts",
      price: 59,
      star: 5,
      username: "Anna Bell",
    },
    {
      id: 2,
      img: "https://images.pexels.com/photos/4145190/pexels-photo-4145190.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1036627/pexels-photo-1036627.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ultra high quality character art with ai",
      price: 79,
      star: 5,
      username: "Lannie Coleman",
    },
    {
      id: 3,
      img: "https://images.pexels.com/photos/8797307/pexels-photo-8797307.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1062280/pexels-photo-1062280.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will creating unique ai generated artworks mid journey ai artist",
      price: 112,
      star: 5,
      username: "Carol Steve",
    },
    {
      id: 4,
      img: "https://images.pexels.com/photos/5708069/pexels-photo-5708069.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom ai generated artwork using your photos",
      price: 99,
      star: 4,
      username: "Don Weber",
    },
    {
      id: 5,
      img: "https://images.pexels.com/photos/5699456/pexels-photo-5699456.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1771383/pexels-photo-1771383.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will recreate your dreams in high quality pictures",
      price: 59,
      star: 5,
      username: "Audrey Richards",
    },
    {
      id: 6,
      img: "https://images.pexels.com/photos/8100784/pexels-photo-8100784.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/715546/pexels-photo-715546.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create ai digital art illustration hyper realistic painting",
      price: 79,
      star: 4,
      username: "Walton Shepard ",
    },
    {
      id: 7,
      img: "https://images.pexels.com/photos/6039245/pexels-photo-6039245.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/720606/pexels-photo-720606.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will generate images with your prompts using ai dalle",
      price: 89,
      star: 5,
      username: "Waverly Schaefer",
    },
    {
      id: 8,
      img: "https://images.pexels.com/photos/5490778/pexels-photo-5490778.jpeg?auto=compress&cs=tinysrgb&w=1600",
      pp: "https://images.pexels.com/photos/1699159/pexels-photo-1699159.jpeg?auto=compress&cs=tinysrgb&w=1600",
      desc: "I will create custom art using midjourney generator",
      price: 110,
      star: 4,
      username: "Wilton Hunt",
    },
  ];